---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bazzua
description: Personal Bazzite image

base-image: ghcr.io/ublue-os/bazzite-nvidia-open
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: bling
    install:
      - 1password

  - type: rpm-ostree
    repos:
      - https://repository.mullvad.net/rpm/stable/mullvad.repo
    install:
      - mullvad-vpn
      - plymouth-plugin-script
      - strace
      - virt-manager

  - type: script
    scripts:
      - 01-extra-packages.sh
      - 02-plymouth.sh

  - type: initramfs

  - type: signing
