---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bazzua
description: Personal Bazzite image

base-image: ghcr.io/ublue-os/bazzite-nvidia-open
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    #    repos:
    #  - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - strace
      - virt-manager

  - type: script
    scripts:
      - 01-extra-packages.sh

  - type: initramfs

  - type: signing
